version: "3.3"
services:
  app-x86:
    build:
      context: ./
      dockerfile: Dockerfile-x86
    volumes:
      - ./:/SandBox
    working_dir: /SandBox
  app-arm:
    build:
      context: ./
      dockerfile: Dockerfile-arm
    volumes:
      - ./:/SandBox
    working_dir: /SandBox
  unittests:
    build:
      context: ./
      dockerfile: Dockerfile-x86
    volumes:
      - ./:/SandBox
    working_dir: /SandBox
