version: "3.8"
services:
  helloworld:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./HelloWorld:/HelloWorld
    working_dir: /HelloWorld
  sandbox:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/SandBox
    working_dir: /SandBox
