version: "3.8"
services:
  app-x86:
    build:
      context: ./
      dockerfile: Dockerfile-x86
    volumes:
      - ./HelloWorld:/HelloWorld
    working_dir: /HelloWorld
  app-arm:
    build:
      context: ./
      dockerfile: Dockerfile-arm
    volumes:
      - ./HelloWorld:/HelloWorld
    working_dir: /HelloWorld
  unittests:
    build:
      context: ./
      dockerfile: Dockerfile-x86
    volumes:
      - ./:/SandBox
    working_dir: /SandBox
