### Generate custom docker image from base
# Note: The base image must be setup with QEMU to allow an x86 
# host to execute ARM targets in this ARM container as most
# CI systems only support x86 hardware.
FROM jgogstad/arm32v7-debian:jessie
RUN apt-get update
RUN apt-get install -y \
	build-essential \
	qt5-qmake \
	qt5-default
COPY scripts/bootstrap-arm.sh /tmp
RUN /tmp/bootstrap-arm.sh

### Eventually the above commands can be removed and replaced with loading a custom docker image
# FROM custom-image