### Generate custom docker image from base
FROM arm32v7/debian
RUN apt-get update
RUN apt-get install -y \
	build-essential \
	qemu-user \
	qt5-qmake \
	qt5-default
COPY scripts/bootstrap-arm.sh /tmp
RUN /tmp/bootstrap-arm.sh

### Eventually the above commands can be removed and replaced with loading a custom docker image
# FROM custom-image