version: 2.1
orbs:
  docker: circleci/docker@1.4.0
jobs:
  Unit-Test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - docker/install-docker-tools
      - run:
          name: Run Tests
          command: |
            docker-compose run unittests 
workflows:
  Test:
    jobs:
      - Docker
      - Unit-Test 
