version: 2.1
jobs:
  Unit-Test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            ls -al
            docker --version
            docker-compose --version
            docker-compose run unittests bash build-unittests.sh
workflows:
  Test:
    jobs:
      - Unit-Test 
