version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            docker-compose run unittests bash build-unittests.sh
  build-x86:
    machine: true
    steps:
      - checkout
      - run:
          name: Build x86 application
          command: |
            docker-compose run app-x86 build-app-x86.sh
            mkdir images
            tar -cvf HelloWorld-x86.tar HelloWorld/HelloWorld
  build-arm:
    machine: true
    steps:
      - checkout
      - run:
          name: Build arm application
          command: |
            sudo apt-get install qemu-user
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker-compose run app-arm build-app-arm.sh
            tar -cvf HelloWorld-arm.tar HelloWorld/HelloWorld
            ls -al images

workflows:
  test_and_build:
    jobs:
      - test
      - build-x86:
          requires:
            - test
      - build-arm:
          requires:
            - test
            - build-x86

