version: 2.1

jobs:
  Unit-Test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            docker-compose run unittests 
 
workflows:
  Test:
    jobs:
      - Unit-Test 
