version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            docker-compose run unittests bash build-unittests.sh
  build-x86:
    machine: true
    steps:
      - checkout
      - run:
          name: Build x86 application
          command: |
            docker-compose run app-x86 build-app-x86.sh
            ls -al
  build-arm:
    machine: true
    steps:
      - checkout
      - run:
          name: Build arm application
          command: |
            docker-compose run app-arm build-app-arm.sh
            ls -al

workflows:
  test_and_build:
    jobs:
      - test
      - build-arm:
          requires:
            - test
