version: 2.1
jobs:
  unittest:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            docker-compose run unittests bash build-unittests.sh
  app-arm:
    machine: true
    steps:
      - run:
          name: Build arm application
          command: |
            docker-compose run app-arm bash build-unittests.sh
            ls -al

workflows:
  test_and_build:
    jobs:
      - unittest
      - app-arm:
        requires:
          - unittest
